var loader_conf;(function(d){d.conf={is_worker:!0}})(loader_conf||(loader_conf={}));var loader_util;(function(d){d.new2DArray=function(a,f){var b,e=Array(a);for(b=0;b<e.length;b++)e[b]=Array(f);return e};d.signedByte=function(a){a%=256;return 128<=a?a-256:a}})(loader_util||(loader_util={}));var loader_wwa_data;
(function(d){var a=function(){return function(){}}();a.ITEMBOX_SIZE=12;a.MAP_ATR_MAX=60;a.OBJ_ATR_MAX=60;a.OLD_MAP_ATR_MAX=40;a.OLD_OBJ_ATR_MAX=40;a.ATR_CROP1=1;a.ATR_CROP2=2;a.ATR_TYPE=3;a.ATR_JUMP_X=16;a.ATR_JUMP_Y=17;a.MAP_LOCALGATE=2;a.OBJECT_RANDOM=16;a.OBJECT_LOCALGATE=18;a.SYSTEM_MESSAGE_NUM=20;a.IMGPOS_DEFAULT_YESNO_X=3;a.IMGPOS_DEFAULT_YESNO_Y=1;a.IMGRELPOS_YESNO_YES_X=0;a.IMGRELPOS_YESNO_NO_X=1;a.IMGRELPOS_YESNO_YESP_X=2;a.IMGRELPOS_YESNO_NOP_X=3;a.IMGPOS_DEFAULT_PLAYER_X=2;a.IMGPOS_DEFAULT_PLAYER_Y=
0;a.IMGPOS_DEFAULT_CLICKABLE_ITEM_SIGN_X=0;a.IMGPOS_DEFAULT_CLICKABLE_ITEM_SIGN_Y=0;a.DEFAULT_DISABLE_SAVE=!1;a.DEFAULT_OLDMAP=!1;a.DEFAULT_OBJECT_NO_COLLAPSE=!1;a.DEFAULT_FRAME_COLOR_R=255;a.DEFAULT_FRAME_COLOR_G=255;a.DEFAULT_FRAME_COLOR_B=255;a.DEFAULT_FRAMEOUT_COLOR_R=96;a.DEFAULT_FRAMEOUT_COLOR_G=96;a.DEFAULT_FRAMEOUT_COLOR_B=96;a.DEFAULT_STR_COLOR_R=0;a.DEFAULT_STR_COLOR_G=0;a.DEFAULT_STR_COLOR_B=0;a.DEFAULT_STATUS_COLOR_R=0;a.DEFAULT_STATUS_COLOR_G=0;a.DEFAULT_STATUS_COLOR_B=0;d.WWAConsts=
a;a=function(){return function(){}}();d.LoaderResponse=a;a=function(){return function(){}}();d.LoaderError=a;a=function(){return function(){}}();d.LoaderProgress=a;(function(a){a[a.MAP=1]="MAP";a[a.OBJECT=0]="OBJECT"})(d.PartsType||(d.PartsType={}));(function(a){a[a.INIT=0]="INIT";a[a.MAP_LOAD=1]="MAP_LOAD";a[a.OBJ_LOAD=2]="OBJ_LOAD";a[a.MAP_ATTR=3]="MAP_ATTR";a[a.OBJ_ATTR=4]="OBJ_ATTR";a[a.RAND_PARTS=5]="RAND_PARTS";a[a.MESSAGE=6]="MESSAGE"})(d.LoadStage||(d.LoadStage={}));a=function(){function a(a,
e){void 0===a&&(a=0);void 0===e&&(e=0);this.x=a;this.y=e}a.prototype.equals=function(a){return this.x===a.x&&this.y===a.y};a.prototype.substract=function(b){return new a(this.x-b.x,this.y-b.y)};a.prototype.clone=function(){return new a(this.x,this.y)};return a}();d.Coord=a;a=function(){return function(){this.systemMessage=this.mapCGName=this.charCGName=this.worldPassNumber=this.worldName=this.message=this.worldPassword=this.objectAttribute=this.mapAttribute=this.mapObject=this.map=this.messageNum=
this.mapWidth=this.itemBox=this.statusGold=this.statusDefence=this.statusStrength=this.statusEnergy=this.statusEnergyMax=this.isOldMap=this.objPartsMax=this.mapPartsMax=this.playerY=this.playerX=this.gameoverY=this.gameoverX=this.version=void 0;this.moves=0;this.statusColorB=this.statusColorG=this.statusColorR=this.fontColorB=this.fontColorG=this.fontColorR=this.frameOutColorB=this.frameOutColorG=this.frameOutColorR=this.frameColorB=this.frameColorG=this.frameColorR=this.imgClickY=this.imgClickX=
this.bgm=this.delPlayerFlag=this.objectNoCollapseDefaultFlag=this.compatibleForOldMapFlag=this.disableSaveFlag=this.clickableItemSignImgPosY=this.clickableItemSignImgPosX=this.playerImgPosY=this.playerImgPosX=this.yesnoImgPosY=this.yesnoImgPosX=void 0}}();d.WWAData=a})(loader_wwa_data||(loader_wwa_data={}));var loader_core;
(function(d){var a=function(){return function(a,e){this.mapData=a;this.extractEndPos=e}}(),f=function(){function b(a){this._fileName=a}b.prototype.requestMapData=function(){var a=this,c=new XMLHttpRequest;try{c.open("GET",this._fileName,!0),c.responseType="arraybuffer",c.onreadystatechange=function(){try{if(c.readyState===XMLHttpRequest.DONE)if(200===c.status||304===c.status)a.loadMapData(c.response),a.sendDataToMainProgram();else{if(404===c.status)throw Error("\u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u300c"+
a._fileName+"\u300d\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3067\u3057\u305f\u3002\nHTTP\u30b9\u30c6\u30fc\u30bf\u30b9\u30b3\u30fc\u30c9\u306f "+c.status+"\u3067\u3059\u3002");if(403===c.status)throw Error("\u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u300c"+a._fileName+"\u300d\u3092\u8aad\u307f\u53d6\u308b\u6a29\u9650\u304c\u306a\u3044\u3088\u3046\u3067\u3059\u3002\n\u7ba1\u7406\u8005\u306e\u65b9\u3078: \u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u306e\u30d1\u30fc\u30df\u30c3\u30b7\u30e7\u30f3\u3092\u78ba\u8a8d\u3057\u3066\u304f\u3060\u3055\u3044\u3002\nHTTP\u30b9\u30c6\u30fc\u30bf\u30b9\u30b3\u30fc\u30c9\u306f "+
c.status+"\u3067\u3059\u3002");throw Error("\u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u300c"+a._fileName+"\u300d\u306e\u8aad\u307f\u8fbc\u307f\u306b\u5931\u6557\u3057\u307e\u3057\u305f\u3002\nHTTP\u30b9\u30c6\u30fc\u30bf\u30b9\u30b3\u30fc\u30c9\u306f "+c.status+"\u3067\u3059\u3002");}}catch(k){a.sendErrorToMainProgram(k)}},c.send(null)}catch(k){this.sendErrorToMainProgram(Error("\u30ed\u30fc\u30c9\u30a8\u30e9\u30fc: \u30ed\u30fc\u30ab\u30eb\u30c6\u30b9\u30c8\u306e\u5834\u5408\u306f\u3001\u30d6\u30e9\u30a6\u30b6\u304c\u5bfe\u5fdc\u3057\u3066\u3044\u306a\u3044\u53ef\u80fd\u6027\u304c\u3042\u308a\u307e\u3059\u3002\n"+
k.message))}};b.prototype.loadMapData=function(a){try{this._srcData=new Uint8Array(a);var c=this.decodeMapData();this._dataExtractor=new WWADataExtractor(c.mapData);this._dataExtractor.extractAllData();this._dataJSObj=this._dataExtractor.getJSObject();this._currentPos=c.extractEndPos}catch(k){throw k;}this._loadAllTextData()};b.prototype._loadAllTextData=function(){var a;30<=this._dataJSObj.version&&(this._dataJSObj.worldPassword=this._getMessageFromData());29>=this._dataJSObj.version&&(this._dataJSObj.messageNum=
b.OLDVER_MESSAGE_MAX);this._dataJSObj.message=Array(this._dataJSObj.messageNum);for(a=0;a<this._dataJSObj.message.length;a++)this._dataJSObj.message[a]=this._getMessageFromData(),0===a%200&&d.sendProgressToMainProgram(a,this._dataJSObj.message.length,loader_wwa_data.LoadStage.MESSAGE);for(;10>this._dataJSObj.messageNum;)this._dataJSObj.message.push(""),this._dataJSObj.messageNum++;d.sendProgressToMainProgram(this._dataJSObj.message.length,this._dataJSObj.message.length,loader_wwa_data.LoadStage.MESSAGE);
this._dataJSObj.worldName=this._getMessageFromData();29>=this._dataJSObj.version?this._dataJSObj.worldPassword=this._getMessageFromData():this._getMessageFromData();this._dataJSObj.worldPassNumber=""===this._dataJSObj.worldPassword?0:29<=this._dataJSObj.version?(parseInt(this._dataJSObj.worldPassword)/10-1197)/17-2357:parseInt(this._dataJSObj.worldPassword);this._dataJSObj.charCGName=this._getMessageFromData();this._dataJSObj.mapCGName=this._getMessageFromData();this._dataJSObj.systemMessage=Array(WWAConsts.SYSTEM_MESSAGE_NUM);
for(a=0;a<WWAConsts.SYSTEM_MESSAGE_NUM;a++)this._dataJSObj.systemMessage[a]=30<=this._dataJSObj.version?this._getMessageFromData():"";this._dataJSObj.yesnoImgPosX=loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_YESNO_X;this._dataJSObj.yesnoImgPosY=loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_YESNO_Y;this._dataJSObj.playerImgPosX=loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_PLAYER_X;this._dataJSObj.playerImgPosY=loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_PLAYER_Y;this._dataJSObj.clickableItemSignImgPosX=loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_CLICKABLE_ITEM_SIGN_X;
this._dataJSObj.clickableItemSignImgPosY=loader_wwa_data.WWAConsts.IMGPOS_DEFAULT_CLICKABLE_ITEM_SIGN_Y;this._dataJSObj.disableSaveFlag=loader_wwa_data.WWAConsts.DEFAULT_DISABLE_SAVE;this._dataJSObj.isOldMap=loader_wwa_data.WWAConsts.DEFAULT_OLDMAP;this._dataJSObj.objectNoCollapseDefaultFlag=loader_wwa_data.WWAConsts.DEFAULT_OBJECT_NO_COLLAPSE;this._dataJSObj.delPlayerFlag=!1;this._dataJSObj.bgm=0;this._dataJSObj.effectCoords=[];this._dataJSObj.effectWaits=0;this._dataJSObj.imgClickX=0;this._dataJSObj.imgClickY=
0;this._dataJSObj.frameColorR=WWAConsts.DEFAULT_FRAME_COLOR_R;this._dataJSObj.frameColorG=WWAConsts.DEFAULT_FRAME_COLOR_G;this._dataJSObj.frameColorB=WWAConsts.DEFAULT_FRAME_COLOR_B;this._dataJSObj.frameOutColorR=WWAConsts.DEFAULT_FRAMEOUT_COLOR_R;this._dataJSObj.frameOutColorG=WWAConsts.DEFAULT_FRAMEOUT_COLOR_G;this._dataJSObj.frameOutColorB=WWAConsts.DEFAULT_FRAMEOUT_COLOR_B;this._dataJSObj.fontColorR=WWAConsts.DEFAULT_STR_COLOR_R;this._dataJSObj.fontColorG=WWAConsts.DEFAULT_STR_COLOR_G;this._dataJSObj.fontColorB=
WWAConsts.DEFAULT_STR_COLOR_B;this._dataJSObj.statusColorR=WWAConsts.DEFAULT_STATUS_COLOR_R;this._dataJSObj.statusColorG=WWAConsts.DEFAULT_STATUS_COLOR_G;this._dataJSObj.statusColorB=WWAConsts.DEFAULT_STATUS_COLOR_B};b.prototype.sendDataToMainProgram=function(){var a=new loader_wwa_data.LoaderResponse;a.progress=null;a.error=null;a.wwaData=this._dataJSObj;sendToMain(a)};b.prototype.sendErrorToMainProgram=function(a){var c=new loader_wwa_data.LoaderResponse;c.wwaData=null;c.progress=null;c.error=new loader_wwa_data.LoaderError;
c.error.name=a.name;c.error.message=a.message;sendToMain(c)};b.prototype.decodeMapData=function(){var e=new Uint8Array(this._srcData.length),c,k,g,h;for(k=c=0;c<this._srcData.length&&(0!==this._srcData[c]||0!==this._srcData[c+1]||0!==this._srcData[c+2]);c++){e[k++]=this._srcData[c];if(this._srcData[c]===this._srcData[c+1]){g=this._srcData[c+2];for(h=0;h<g;h++)e[k++]=this._srcData[c];c+=2}k+255>=e.length&&(g=new Uint8Array(e.length+b.MEM_BLOCK),g.set(e),e=g)}try{console.log("EXTRACT DATA = "+k+" "+
c)}catch(n){}try{this.checkCompletelyDecoded(e,k)}catch(n){throw n;}return new a(e,c+b.EXT_LAST_PADDING)};b.prototype._getMessageFromData=function(){for(var a="",c=0;1500>c&&(0!=this._srcData[this._currentPos+2*c]||0!=this._srcData[this._currentPos+2*c+1]);c++)a+=String.fromCharCode((this._srcData[this._currentPos+2*c+1]<<8)+this._srcData[this._currentPos+2*c]);this._currentPos+=2*c+2;return a};b.prototype.checkCompletelyDecoded=function(a,c){var b,e=a[WWADataExtractor.POS_CHECK]+256*a[WWADataExtractor.POS_CHECK+
1],h=0;if(29<=a[WWADataExtractor.POS_VERSION]){for(b=2;b<c;b++)h+=util.signedByte(a[b])*(b%8+1);h=h%65536&65535;if(e!==h)throw Error("\u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u304c\u58ca\u308c\u3066\u3044\u308b\u3088\u3046\u3067\u3059\u3002\n \u30c1\u30a7\u30c3\u30af\u30b5\u30e0\u306e\u5024\u306f"+e+"\u3067\u3059\u304c\u3001\u5b9f\u969b\u306e\u548c\u306f"+h+"\u3067\u3057\u305f\u3002");}};return b}();f.MEM_BLOCK=65E3;f.EXT_LAST_PADDING=3;f.OLDVER_MESSAGE_MAX=400;d.WWALoader=f;d.sendProgressToMainProgram=
function(a,e,c){var b=new loader_wwa_data.LoaderResponse;b.error=null;b.wwaData=null;b.progress=new loader_wwa_data.LoaderProgress;b.progress.current=a;b.progress.total=e;b.progress.stage=c;sendToMain(b)}})(loader_core||(loader_core={}));var loader_extractor;
(function(d){var a=loader_wwa_data.PartsType,f=function(){function b(a){this._bitData=a;this._wwaData=new WWAData}b.prototype.extractAllData=function(){var e,c;this._wwaData.version=this._bitData[b.POS_VERSION];this._extractInitialParameters();this._currentPosition=29<=this._wwaData.version?b.POS_MAPDATA_TOP:b.POS_OLD_MAPDATA_TOP;this._wwaData.map=this._getFieldDataFromBits(loader_wwa_data.PartsType.MAP,this._wwaData.mapPartsMax).concat();this._wwaData.mapObject=this._getFieldDataFromBits(loader_wwa_data.PartsType.OBJECT,
this._wwaData.objPartsMax).concat();e=29<this._wwaData.version?WWAConsts.MAP_ATR_MAX:WWAConsts.OLD_MAP_ATR_MAX;c=29<this._wwaData.version?WWAConsts.OBJ_ATR_MAX:WWAConsts.OLD_OBJ_ATR_MAX;this._wwaData.mapAttribute=this._getPartsDataFromBits(loader_wwa_data.PartsType.MAP,this._wwaData.mapPartsMax,e).concat();this._wwaData.objectAttribute=this._getPartsDataFromBits(loader_wwa_data.PartsType.OBJECT,this._wwaData.objPartsMax,c).concat();29>=this._wwaData.version&&(this._convertAttributeV2toV3(a.MAP),this._convertAttributeV2toV3(a.OBJECT));
this._replaceAllRandomObjects()};b.prototype._convertAttributeV2toV3=function(b){var c,e;if(b==a.MAP)b=this._wwaData.mapPartsMax,c=this._wwaData.mapAttribute,e=WWAConsts.MAP_LOCALGATE;else if(b==a.OBJECT)b=this._wwaData.objPartsMax,c=this._wwaData.objectAttribute,e=WWAConsts.OBJECT_LOCALGATE;else throw Error("\u8b0e\u306e\u30d1\u30fc\u30c4\u7a2e\u5225\u304c\u6307\u5b9a\u3055\u308c\u307e\u3057\u305f");for(var g=0;g<b;g++){for(var h=9;0<=h;h--){var d=c[g][20+2*h]&255,f=c[g][20+2*h]>>8,l=c[g][2*h+21]&
255,m=c[g][2*h+21]>>8;250===l?l=9E3:100<l&&(l+=9840);250===m?m=9E3:100<m&&(m+=9840);c[g][20+4*h]=d;c[g][4*h+23]=f;c[g][4*h+21]=l;c[g][4*h+22]=m}c[g][WWAConsts.ATR_TYPE]===e&&(100<c[g][WWAConsts.ATR_JUMP_X]&&(c[g][WWAConsts.ATR_JUMP_X]+=9840),100<c[g][WWAConsts.ATR_JUMP_Y]&&(c[g][WWAConsts.ATR_JUMP_Y]+=9840))}};b.prototype.getJSObject=function(){return this._wwaData};b.prototype._get1ByteNumber=function(a){return this._bitData[a]};b.prototype._get2BytesNumber=function(a){return this._bitData[a]+256*
this._bitData[a+1]};b.prototype._extractInitialParameters=function(){29<this._wwaData.version?(this._wwaData.gameoverX=this._get2BytesNumber(b.POS_GAMEOVER_X),this._wwaData.gameoverY=this._get2BytesNumber(b.POS_GAMEOVER_Y),this._wwaData.playerX=this._get2BytesNumber(b.POS_PLAYER_X),this._wwaData.playerY=this._get2BytesNumber(b.POS_PLAYER_Y),this._wwaData.mapPartsMax=this._get2BytesNumber(b.POS_MAP_COUNT),this._wwaData.objPartsMax=this._get2BytesNumber(b.POS_OBJ_COUNT),this._wwaData.isOldMap=!1):(this._wwaData.gameoverX=
this._get1ByteNumber(b.POS_OLD_GAMEOVER_X),this._wwaData.gameoverY=this._get1ByteNumber(b.POS_OLD_GAMEOVER_Y),this._wwaData.playerX=this._get1ByteNumber(b.POS_OLD_PLAYER_X),this._wwaData.playerY=this._get1ByteNumber(b.POS_OLD_PLAYER_Y),this._wwaData.mapPartsMax=this._get1ByteNumber(b.POS_OLD_MAP_COUNT),this._wwaData.objPartsMax=this._get1ByteNumber(b.POS_OLD_OBJ_COUNT),this._wwaData.isOldMap=!0);this._wwaData.statusEnergyMax=this._get2BytesNumber(b.POS_STATUS_ENERGY_MAX);this._wwaData.statusEnergy=
this._get2BytesNumber(b.POS_STATUS_ENERGY);this._wwaData.statusStrength=this._get2BytesNumber(b.POS_STATUS_STRENGTH);this._wwaData.statusDefence=this._get2BytesNumber(b.POS_STATUS_DEFENCE);this._wwaData.statusGold=this._get2BytesNumber(b.POS_STATUS_GOLD);this._extractInitialItemData();this._wwaData.mapWidth=this._get2BytesNumber(b.POS_MAP_SIZE);this._wwaData.messageNum=this._get2BytesNumber(b.POS_MESSAGE_NUM);28>this._wwaData.version?this._wwaData.mapWidth=71:29>=this._wwaData.version&&(this._wwaData.mapWidth=
101)};b.prototype._extractInitialItemData=function(){var a,c=29<this._wwaData.version?b.POS_ITEMBOX_TOP:b.POS_OLD_ITEMBOX_TOP;this._wwaData.itemBox=Array(WWAConsts.ITEMBOX_SIZE);for(a=0;a<WWAConsts.ITEMBOX_SIZE;a++)this._wwaData.itemBox[a]=this._get1ByteNumber(c+a)};b.prototype._getFieldDataFromBits=function(a,c){var b,g,e;e=util.new2DArray(this._wwaData.mapWidth,this._wwaData.mapWidth);for(b=0;b<this._wwaData.mapWidth;b++)for(g=0;g<this._wwaData.mapWidth;g++)29<this._wwaData.version?(e[b][g]=this._get2BytesNumber(this._currentPosition),
this._currentPosition+=2):(e[b][g]=this._get1ByteNumber(this._currentPosition),this._currentPosition+=1),0===(b*this._wwaData.mapWidth+g)%200&&loader_core.sendProgressToMainProgram(b*this._wwaData.mapWidth+g,this._wwaData.mapWidth*this._wwaData.mapWidth,a===loader_wwa_data.PartsType.MAP?loader_wwa_data.LoadStage.MAP_LOAD:loader_wwa_data.LoadStage.OBJ_LOAD),e[b][g]>=c&&(e[b][g]=0);loader_core.sendProgressToMainProgram(this._wwaData.mapWidth*this._wwaData.mapWidth,this._wwaData.mapWidth*this._wwaData.mapWidth,
a===loader_wwa_data.PartsType.MAP?loader_wwa_data.LoadStage.MAP_LOAD:loader_wwa_data.LoadStage.OBJ_LOAD);return e};b.prototype._getPartsDataFromBits=function(a,b,d){var c,e,f;f=util.new2DArray(b,d);for(c=0;c<b;c++)for(e=0;e<d;e++)0===(c*this._wwaData.mapWidth+e)%200&&loader_core.sendProgressToMainProgram(c*d+e,b*d,a===loader_wwa_data.PartsType.MAP?loader_wwa_data.LoadStage.MAP_ATTR:loader_wwa_data.LoadStage.OBJ_ATTR),f[c][e]=e===WWAConsts.ATR_CROP1||e===WWAConsts.ATR_CROP2?0:this._get2BytesNumber(this._currentPosition),
this._currentPosition+=2;loader_core.sendProgressToMainProgram(b*d,b*d,a===loader_wwa_data.PartsType.MAP?loader_wwa_data.LoadStage.MAP_ATTR:loader_wwa_data.LoadStage.OBJ_ATTR);return f};b.prototype._replaceAllRandomObjects=function(){loader_core.sendProgressToMainProgram(this._wwaData.mapWidth*this._wwaData.mapWidth,this._wwaData.mapWidth*this._wwaData.mapWidth,loader_wwa_data.LoadStage.RAND_PARTS)};b.prototype._replaceRandomObject=function(a,b,d){a=this._wwaData.objectAttribute[a][10+Math.floor(10*
Math.random())];a>=this._wwaData.objPartsMax&&(a=0);this._wwaData.mapObject[b][d]=a};return b}();f.POS_CHECK=0;f.POS_VERSION=2;f.POS_OLD_MAP_COUNT=3;f.POS_OLD_OBJ_COUNT=4;f.POS_OLD_PLAYER_X=5;f.POS_OLD_PLAYER_Y=6;f.POS_STATUS_ENERGY=10;f.POS_STATUS_STRENGTH=12;f.POS_STATUS_DEFENCE=14;f.POS_STATUS_GOLD=16;f.POS_OLD_GAMEOVER_X=18;f.POS_OLD_GAMEOVER_Y=19;f.POS_OLD_ITEMBOX_TOP=20;f.POS_STATUS_ENERGY_MAX=32;f.POS_MAP_COUNT=34;f.POS_OBJ_COUNT=36;f.POS_PLAYER_X=38;f.POS_PLAYER_Y=40;f.POS_GAMEOVER_X=42;f.POS_GAMEOVER_Y=
44;f.POS_MAP_SIZE=46;f.POS_MESSAGE_NUM=48;f.POS_ITEMBOX_TOP=60;f.POS_MAPDATA_TOP=90;f.POS_OLD_MAPDATA_TOP=100;d.WWADataExtractor=f})(loader_extractor||(loader_extractor={}));function sendToMain(d){loader_conf.conf.is_worker?postMessage(d):postMessage_noWorker({data:d})}var util=loader_util,WWAConsts=loader_wwa_data.WWAConsts,WWAData=loader_wwa_data.WWAData,WWADataExtractor=loader_extractor.WWADataExtractor,WWALoader=loader_core.WWALoader;
function loader_start(d){void 0!==d.data.fileName?(new WWALoader(d.data.fileName)).requestMapData():(d=new loader_wwa_data.LoaderResponse,d.wwaData=null,d.progress=null,d.error=new loader_wwa_data.LoaderError,d.error.name="",d.error.message="\u30de\u30c3\u30d7\u30c7\u30fc\u30bf\u306e\u30d5\u30a1\u30a4\u30eb\u540d\u304c\u6307\u5b9a\u3055\u308c\u3066\u3044\u307e\u305b\u3093\u3002",sendToMain(d))}loader_conf.conf.is_worker&&addEventListener("message",loader_start);
